# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 92a3d4a3876bafea77fd83e14015d13d152b29d9e7427fc23a38ef74717636f969dfb6104d2801a818d2171fa509b173c2e57be0b33a65ce5b96b34db3571de8

test:
  secret_key_base: 54dcd89fed3435c0259b2ceae8b9dd499c5a25792e46b3d2078b478a9b4015d1c76d601c5ffca0322678be901d48a4784b56067099fdad7cf7af03b20ed98435

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
